fos_ck_editor:
     input_sync: true
     default_config: base_config
     configs:
         base_config:
             toolbar:
                 -
                     name: "styles"
                     items: ['Format', 'Bold', 'Italic', 'BulletedList', 'Link', 'Unlink']

easy_admin:
    site_name: '%site_name%'
    design:
        assets:
            css:
                - 'assets/dist/css/easyadmin.css'

        form_theme:
            - '@EasyAdmin/form/bootstrap_4.html.twig'
            - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
            - 'form/elfinder_widget.html.twig'

    entities:
        Survey:
            class: App\Entity\Survey
            templates:
                new: 'easy_admin/Survey/new.html.twig'
                edit: 'easy_admin/Survey/edit.html.twig'

            list:
                actions:
                    - shareSurvey
                    - show
                    - edit
                    - '-delete'

                fields:
                    - property: title
                      # template: share.html.twig
                    - property: description
                      template: easy_admin/richtext.html.twig
                      richtext:
                          max_length: 80
                    - property: questions
                    - property: answers
                      template: easy_admin/Survey/answers.html.twig
                    - property: createdAt

            show:
                actions:
                    - '-delete'

                fields:
                    - property: title
                    - property: answers
                      template: easy_admin/Survey/answers.html.twig

            form:
                fields:
                    - property: title
                    - property: description
                      type: fos_ckeditor
                    - property: instructions
                      type: fos_ckeditor
                    - property: preparations
                      type: fos_ckeditor
                      help: 'Use <code>survey://all_questions</code> to insert the url to all survey questions'
                    - property: configuration
                      type: App\Form\Type\ConfigurationType
                    - property: questions
                      type: collection
                      type_options:
                        entry_type: App\Form\Type\QuestionType
                        by_reference: false
                        required: true
                      embedded: true

        Answer:
            class: App\Entity\Answer
            disabled_actions: [edit]
            list:
                actions:
                    - name: answer_show
                      type: route
                      label: action.show
                    - name: answer_edit
                      type: route
                      label: action.edit
                fields:
                    - property: survey
                    - property: name
                    - property: company
                    - property: documentationId
                    - property: address
                    - property: description
                    - property: createdAt

        User:
            class: App\Entity\User
            list:
                fields:
                    - property: email
                    - property: roles
                    - property: lastLoggedInAt
                      type: datetime

                actions:
                  -
                    label: 'Set password'
                    name: setUserPassword
                    # name: admin_user_set_password
                    # type: route

            form:
                fields:
                    - property: email
                      type: email
                    - property: roles
                      type: choice
                      type_options:
                          multiple: true
                          expanded: true
                          choices: &role_list
                              ROLE_USER: ROLE_USER
                              ROLE_ADMIN: ROLE_ADMIN

        Setting:
            controller: ItkDev\ConfigBundle\Controller\SettingController
            class: ItkDev\ConfigBundle\Entity\Setting
            disabled_actions: [new, delete]
            list:
                fields:
                    - property: name
                    - property: description
                    - property: value
                      label: Value
                      template: '@ItkDevConfig/easy_admin/Setting/display_value.html.twig'

            edit:
                fields:
                    - property: name
                      type_options:
                          disabled: true
