<?php

namespace App\Controller\Admin;

use App\Entity\User;
use Doctrine\ORM\EntityManagerInterface;
use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use EasyCorp\Bundle\EasyAdminBundle\Config\Action;
use EasyCorp\Bundle\EasyAdminBundle\Config\Actions;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;
use EasyCorp\Bundle\EasyAdminBundle\Field\ArrayField;
use EasyCorp\Bundle\EasyAdminBundle\Field\ChoiceField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextareaField;
use EasyCorp\Bundle\EasyAdminBundle\Field\CollectionField;
use EasyCorp\Bundle\EasyAdminBundle\Field\AssociationField;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;

class UserCrudController extends AbstractCrudController
{
    private UserPasswordHasherInterface $hasher;

    public static function getEntityFqcn(): string
    {
        return User::class;
    }

    public function __construct(UserPasswordHasherInterface $hasher)
    {
        $this->hasher = $hasher;
    }

    public function persistEntity(EntityManagerInterface $entityManager, $entityInstance): void
    {
        function random_str(
            int $length = 8,
            string $keyspace = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'
        ): string {
            if ($length < 1) {
                throw new \RangeException("Length must be a positive integer");
            }
            $pieces = [];
            $max = mb_strlen($keyspace, '8bit') - 1;
            for ($i = 0; $i < $length; ++$i) {
                $pieces []= $keyspace[random_int(0, $max)];
            }
            return implode('', $pieces);
        }

        $myRandomPassword = random_str();

        $entityInstance->setPassword($this->hasher->hashPassword($entityInstance, $myRandomPassword));

        parent::persistEntity($entityManager, $entityInstance); // TODO: Change the autogenerated stub
    }

    public function configureFields(string $pageName): iterable
    {
        $email = TextField::new('email');
        $roles = ArrayField::new('roles');
        $assoc_roles = ChoiceField::new('roles')->setChoices([
            'User' => "ROLE_USER",
            'Admin' => "ROLE_ADMIN",

        ])->allowMultipleChoices(true)->renderExpanded();
        // $random = textfield::new('password')->


        if (Crud::PAGE_INDEX === $pageName) {
            return [$email, $roles];
        }elseif (Crud::PAGE_NEW === $pageName) {
            return [$email, $assoc_roles];
        }elseif (Crud::PAGE_EDIT === $pageName) {
            return [$email, $assoc_roles];
        }
    }

}
