<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMO7quWM\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMO7quWM/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMO7quWM.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMO7quWM\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMO7quWM\App_KernelDevDebugContainer([
    'container.build_hash' => 'MO7quWM',
    'container.build_id' => 'b3af34a2',
    'container.build_time' => 1666700401,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMO7quWM');
