<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXxq5ZRJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXxq5ZRJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXxq5ZRJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXxq5ZRJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXxq5ZRJ\App_KernelDevDebugContainer([
    'container.build_hash' => 'Xxq5ZRJ',
    'container.build_id' => '9ef5f59b',
    'container.build_time' => 1667297340,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXxq5ZRJ');
