<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKhgsB0G\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKhgsB0G/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKhgsB0G.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKhgsB0G\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKhgsB0G\App_KernelDevDebugContainer([
    'container.build_hash' => 'KhgsB0G',
    'container.build_id' => '13199f0a',
    'container.build_time' => 1667296485,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKhgsB0G');
